# Generated by Django 5.2.8 on 2025-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=256)),
                ('expirationTimeDays', models.PositiveIntegerField()),
                ('costPerUnit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
