# Generated by Django 5.2.8 on 2025-11-30 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_consumptionlog_userinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionlog',
            options={'ordering': ['-consumption_date']},
        ),
        migrations.AlterModelOptions(
            name='userinventory',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AddIndex(
            model_name='consumptionlog',
            index=models.Index(fields=['user', '-consumption_date'], name='api_consump_user_id_335cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', '-purchase_date'], name='api_userinv_user_id_374b00_idx'),
        ),
    ]
